version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=deResearcher
      - POSTGRES_PASSWORD=deResearcher
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "6000:6000"
volumes:
  postgres:
